---
title: "PCA Practice"
author: "Justin"
date: "10/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Using PCA

use prcomp() to do PCA

```{r}
# Download file

mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1)

# Shows first 6 lines of data plot

head(mydata)

# Find dimensions with dim(); outputs Row, Col

dim(mydata)

# Do PCA

pca <- prcomp(t(mydata), scale=TRUE) 


# See what is returned by the prcomp() function
attributes(pca) 

# Basic PC1 v PC2 plot

plot(pca$x[,1], pca$x[,2])

# Variance captured per PC
pca.var <- pca$sdev^2 

# Last digit specifies number of decimal places the variance goes out to

pca.var.per <- round(pca.var/sum(pca.var)*100, 1) 

# Print, tells you how much variance there is per column; EX: 92.6% variance in column 1, etc

pca.var.per


barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")


## A vector of colors for wt and ko samples

colvec <- colnames(mydata)
colvec[grep("wt", colvec)] <- "red"
colvec[grep("ko", colvec)] <- "blue"

plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 


# Click to identify which sample is which
identify(pca$x[,1], pca$x[,2], labels=colnames(mydata)) 


```


```{r}
# Import and Read the file

uk <- read.csv("UK_foods.csv", row.names = 1)
```


```{r}
# Using View(), head(), and tail()

View(uk)

head(uk)

tail(uk)

dim(uk)

# Barplot work; beside=T makes bars side by side; beside=F makes bars stacked

barplot(as.matrix(uk), beside=T, col=rainbow(nrow(uk)))

barplot(as.matrix(uk), beside=F, col=rainbow(nrow(uk)))

# Pairwise plot

pairs(uk, col=rainbow(10), pch=16)

pca <- prcomp(t(uk))
summary(pca)


```

```{r}
# plot

pca <- prcomp(t(uk))
summary(pca)

plot((pca$x[,1]), (pca$x[,2]))














```

